### ISSUE TITLE
How to use CHAP on multiple ion channels

### ISSUE THREAD

**Issue by cgseitz** [channotation/chap#35]
Hello,

I am wanting to use CHAP with my system, which contains several putative ion channels. What is the best way to go about this? From reading the documentation, I can think of a few ideas:

1) Run CHAP multiple times, with each time setting the ```-pf-init-probe-pos``` to be over each ion channel
2) Slice my trajectories so that each one just contains one ion channel
3) Tell CHAP that there are multiple ion channels in the system (unclear exactly how to do this, would need syntax examples)

What would you recommend? This is a huge system, is why I'm asking for your recommendations instead of trying each of these. Thanks in advance!

Best,
Christian

**Comment by Inniag** [comment]
Hi Christian, thanks for reaching out.

Unfortunately, CHAP can not identify multiple pathways simultaneously, which rules out your option number 3. The other two options should both work and it is up to your personal preference which one you chose. The `-pf-init-probe-pos` exists for this purpose, but I have found it can sometimes be easier for scripting purposes to just position the ion channel in the box so that the center of the pore lies in the origin. How easy this would be in your case, you are in the best position to judge.

Hope this helps and best of luck with your research!
